### ISSUE TITLE
Browser based zoom (for arm)

### ISSUE THREAD

**Issue by aykborstelmann** [kastldratza/zoomrec#18]
I was trying to run this project on a raspberry pi 4 but the problem is that zoom doesn't offer an arm client. 
While I did not know this project, I started building something similar (https://github.com/aykborstelmann/zoom-recorder), but using the zoom browser client.
If there is interest for this, I can try integrating this and by that offer an arm (and all other now currently supported platforms) solution for recording zoom meetings.

P.S. I really like this project, excellent job!

**Comment by v1nc** [comment]
Good work.
You can also run the zoom client on arm with x86 emulation, [here](https://github.com/v1nc/zoomrec/blob/master/Dockerfile) is my Dockerfile to run zoomrec based on [anujdatar/box86](https://github.com/ptitSeb/box86).

Be aware that building the Dockerfile will take ages :sweat_smile:

**Comment by aykborstelmann** [comment]
Oh nice, I will have a look at this. If this works smoothly this would of course be a better option.

**Comment by uriafranko** [comment]
Consider running docker with 
`--platform linux/amd64` as a flag.

It will emulate docker as amd64 for you.
