### ISSUE TITLE
SESSION_MANAGER environment variable not defined

### ISSUE THREAD

**Issue by jnthnw** [kastldratza/zoomrec#21]
When I try to start the container I get the following error:

```DISPLAY = :1
VNC_COL_DEPTH = 24
VNC_RESOLUTION = 1024x576
VNC_IP = 172.17.0.2
VNC_PORT = 5901

Connect to 172.17.0.2:5901

Start script..
Failed to connect to session manager: Failed to connect to the session manager: SESSION_MANAGER environment variable not defined
```

tested on Debian GNU/Linux 10 (buster)

**Comment by kastldratza** [comment]
Hi @jnthnw, do you still have this problem?
The Error message is displayed every time, but it should still work. I will fix this when refactoring.

**Comment by Guyv-dev** [comment]
I am expressing this problem also, and i can't connect via vnc.
can i define this var before your fix?
thanks

**Comment by kastldratza** [comment]
@Guyv-dev The error message is always issued, but does not affect zoomrec. What is the error message when connecting via VNC?

**Comment by Guyv-dev** [comment]
I am getting 'unable to connect' when i try to connect with vnc client. I tried couple of vnc clients and gets the same output.
Although i cant connect, the port is in fact open and in LISTEN state

> $ netstat -tulnp
> 
> (Not all processes could be identified, non-owned process info
>  will not be shown, you would have to be root to see it all.)
> Active Internet connections (only servers)
> Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
> tcp6       0      0 :::5901                 :::*                    LISTEN      -  
> tcp        0      0 0.0.0.0:5901            0.0.0.0:*               LISTEN      - 

But the bigger problem i face is that it doesnt  seems  to record.  my settings are:                                                         

> sudo docker run -d --restart unless-stopped \
>   -v /home/duser/recordings:/home/zoomrec/recordings \
>   -v /home/duser/audio:/home/zoomrec/audio \
>   -v /home/duser/meetings.csv:/home/zoomrec/meetings.csv:ro \
>   -p 5901:5901 \
>   --name zoomrec \
> kastldratza/zoomrec:latest

meetings.csv:

> weekday;time;duration;id;password;description;record
> sunday;11:25;70;url;;des;true;

i am running docker 20.10.10 build b485636 on debain 11.

**Comment by EdisonJwa** [comment]
> @Guyv-dev The error message is always issued, but does not affect zoomrec. What is the error message when connecting via VNC?
Here's the error

![Snipaste_2021-11-18_14-54-56](https://user-images.githubusercontent.com/22003734/142360163-2026f856-9f2a-4f0e-95d7-b128f7f96d45.png)

**Comment by EdisonJwa** [comment]
> @Guyv-dev The error message is always issued, but does not affect zoomrec. What is the error message when connecting via VNC?

Here's the error

![Snipaste_2021-11-18_14-54-56](https://user-images.githubusercontent.com/22003734/142360295-d88da75c-0e36-4cd0-b9c6-66b61d18ebe7.png)

**Comment by Guyv-dev** [comment]
Actually, it was my mistake, an embarrassing one, I thought that port 5901 is the default port for vnc. So it's working for me. 
By the way, I would love to see 3 more features in your next build:
1. To be able to change the crt value, zero creates extremely large files.
2. Automatically minimize the participant's window and move the bar to the top.
3. Stop the loop (after some time) that waits for the zoom meeting to start. When the zoom meeting hasn't occurred eventually, the script keeps waiting forever.
