### ISSUE TITLE
Replace Zoom Launch with xdg-open

### ISSUE THREAD

**Issue by RoboBlawck** [kastldratza/zoomrec#24]
Currently, zoomrec attempts to use a new zoom instance to input the meeting id, passcode, and name. An easier alternative would be to execute the command:

`xdg-open "--url=zoommtg://zoom.us/join?action=join&confno=$id&pwd=$pwd&uname=$name"`

which should automatically launch a zoom meeting with the right information without it being manually inputed by the script.

This means you do not have to recode the script if the UI for inputting the meeting id, passcode, or name changes drastically. 

You also do not need to code seperate mechanisms for each different method of joining a meeting, as only xdg-open will be required.

More control options from the url scheme. 

On a personal note, I use a modified docker container with firefox installed to manually sign in since the zoom meetings I attend requires an aunthenticated google account, and there appears to be no way to manually sign in via Google unless with a web browser. Unfortunately it is not possible to record any zoom meeting with any existing account since the current script requires any existing zoom instances to be killed, potentionally signing  my account out in the process. 

Implementing this change should allow users to join with an existing account that is already signed in, since no zoom process will need to be killed. If users are given the choice to manually sign in to record their meetings with their account, no action is required from the developers part to securecly authenticate the accounts since that would already be handled by the user.

**Comment by kastldratza** [comment]
Thank you! I will keep that in mind when refactoring. :+1: 
The use of an existing account is already planned and on the roadmap. I will face this after the refactoring.

However, your command does not work for me. This is how it would work:
`xdg-open "zoommtg://zoom.us/join?action=join&confno=$id&pwd=$pwd&uname=$name"`
