### ISSUE TITLE
Using Telegram Bot to remotely start a join/recording

### ISSUE THREAD

**Issue by PalmLP** [kastldratza/zoomrec#26]
Hey there,

Sometimes, our university uses Zoom calls to repeat "important topics" (questions) for our upcoming exams. This causes everyone to send messages to their colleagues and rushing to their computers. 

I would love to just send a telegram message so that the bot joins this meeting and records it. Maybe, an option to store meetingId-passcode-combinations and giving it a nickname (math1...) could help with this.

I love your project :D 

Kind regards,
Max

**Comment by kastldratza** [comment]
Hey @PalmLP 
that sounds good to me. I'll give it some thought and add it to the roadmap. If you've already worked on it, feel free to create a pull request as well.
