### ISSUE TITLE
Customize what exactly to record during a meeting

### ISSUE THREAD

**Issue by almayor** [kastldratza/zoomrec#28]
Sometimes I need to record not only the speaker's shared screen but also

* the speaker's webcam (e.g. if they're writing something on a physical whiteboard, in addition to slides)
* the chatroom

This could be specified in a separate field of the `meeting.csv, with letter-based options. Examples:

`S` – record just the screen
`SW` – record screen and webcam
`WC` – record webcam and chat

I think it'd be possible to implement using additional instructions to `pyautogui`

**Comment by kastldratza** [comment]
Good idea. Yes, it would be possible to implement this. But you have to keep in mind that this can also change during the meeting, for example if the webcam or screen transmission is turned on/off. This also needs to be addressed.

I will add this to the roadmap.
