### ISSUE TITLE
Hardware Transcoding

### ISSUE THREAD

**Issue by eldadh** [kastldratza/zoomrec#29]
**Is your feature request related to a problem? Please describe.**
Its not a real problem but the files are huge

**Describe the solution you'd like**
since using ffmpeg i would like a general vaapi  transcoding feature 

**Describe alternatives you've considered**
At the moment i am post processing the video files

**Additional context**

**Comment by Robin-Bakker** [comment]
Some of the improvements in #25 reduce file size through the use of h.264 encoding.

**Comment by eldadh** [comment]
Perhaps make a "2 pass" method instead of only running once during the recording 
the first pass is during the live recording session - with minimal loss and resources 
and the second is "post-process" for tighter compression 
and perhaps use  another flag in the csv file for post processes, for small file size
