### ISSUE TITLE
Explain How To Run

### ISSUE THREAD

**Issue by muhammetaydinn** [kastldratza/zoomrec#31]
I'm not very knowledgeable about Docker and Python.
Can you share a video or resource where you explain how to run the bot?

**Comment by kastldratza** [comment]
As described in the README, you can see how to get started with Docker on this page.
https://www.docker.com/get-started

Here is also a video explaining Docker.
https://www.youtube.com/watch?v=iqqDU2crIEQ

And you don't necessarily need to understand the Python code to use zoomrec.

**Comment by Hamza-Kamran** [comment]
Is it possible to record a video running Docker and Python code? It seems I have major problems in getting zoomrec to work

**Comment by Hamza-Kamran** [comment]
> As described in the README, you can see how to get started with Docker on this page. https://www.docker.com/get-started
> 
> Here is also a video explaining Docker. https://www.youtube.com/watch?v=iqqDU2crIEQ
> 
> And you don't necessarily need to understand the Python code to use zoomrec.

Maybe a video will be helpful in how to run zoomrec. I have followed the instructions but it still doesn't work. It is unable to click on "Join a Meeting"
