### ISSUE TITLE
ERROR: SESSION_MANAGER environment variable not defined 

### ISSUE THREAD

**Issue by HappyMiner** [kastldratza/zoomrec#37]
**Describe the bug**
I downloaded ghcr.io/kastldratza/zoomrec and I am trying to run it under MacOS 10.15.7 (Catalina). 

I created the parts mentioned in "Preparation":
mkdir -p recordings/screenshots
chown -R 1000:1000 recordings

mkdir -p audio
chown -R 1000:1000 audio

Command used to run it:
docker run -v $(pwd)/recordings:/home/zoomrec/recordings \
-v $(pwd)/example/audio:/home/zoomrec/audio \
-v $(pwd)/example/meetings.csv:/home/zoomrec/meetings.csv:ro \
-p 8081:8081 --security-opt seccomp:unconfined kastldratza/zoomrec

I removed the "-d --restart unless-stopped" bit in order to be able to see an error message. It was a pain to stop docker from restarting this container and finally get rid of it.

The output I am then getting is:
> Mac:zoomrec User$ docker run -v $(pwd)/recordings:/home/zoomrec/recordings \
> -v $(pwd)/example/audio:/home/zoomrec/audio \
> -v $(pwd)/example/meetings.csv:/home/zoomrec/meetings.csv:ro \
> -p 8081:8081 --security-opt seccomp:unconfined kastldratza/zoomrec
>
> DISPLAY = :1
> VNC_COL_DEPTH = 24
> VNC_RESOLUTION = 1024x576
> VNC_IP = 172.17.0.2
> VNC_PORT = 5901
>
> Connect to 172.17.0.2:5901
>
> Start script..
> Failed to connect to session manager: Failed to connect to the session manager: SESSION_MANAGER environment 
> variable not defined

**To Reproduce**
1. Download the image through docker hub: https://hub.docker.com/r/kastldratza/zoomrec
2. Complete "preparations" section
3. Run docker command above

**Expected behavior**
I expect to be able to login through VNC and launch and configure zoom.

**Screenshots**
N/A see console output above.

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.7 (Catalina)
 - Docker 4.7.1 (77678)

**Comment by roperjonathan** [comment]
Having the same issue but on Windows. Using same command (adapted for Windows CLI) and get same output

**Desktop (please complete the following information):**

OS: Windows 10 19044.1645
Docker 4.7.1 (77678)

Have tried suggestions from #32 but none appear to work.

**Comment by jo-te** [comment]
Hey, I assume that the error you see is actually a warning you can ignore and not the cause that it doesn't work for you.
I see this message too in the logs although everything works correctly. 
Check if your `meetings.csv` is formatted correctly using `;` as delimiter.
This was the mistake I made, because I just copied the table of the README markdown file where the delimiter is `|`. If this is nothing you did, I still strongly assume that you made anywhere a little mistake which causes that it doesn't work so anyway the issue here is that you do not get any helpful error message.

**Comment by roperjonathan** [comment]
Hi in my case, I didn't provide a meetings.csv. Would that be an issue?

**Comment by jo-te** [comment]
> Hi in my case, I didn't provide a meetings.csv. Would that be an issue?
How did you than specify the Zoom meeting to be recorded?

**Comment by danyanyam** [comment]
I also noticed, that app is restarted when you run container outside the folder with code, so make sure you are running instance within the repo

**Comment by juanalvarez9591** [comment]
Having the same problem... Really desperate for an answer

**Comment by juanalvarez9591** [comment]
When I try to assign from docker env variables a random boolean for SESSION MANAGER it says _IceTransOpen: Unable to Parse address 0
Failed to connect to session manager: Failed to connect to the session manager: Could not open network socket
