### ISSUE TITLE
Zoom not ready yet - despite zoom connected and running

### ISSUE THREAD

**Issue by BigYellowHammer** [kastldratza/zoomrec#38]
**Describe the bug**
I just took latest version and videos are not being recorded.
Its looping with **Zoom not ready yet**

**Screenshots**
![zoomrec](https://user-images.githubusercontent.com/6392942/181800070-8b55ca02-fc04-4a74-99cc-55248270108f.PNG)

Zoom version in container is 5.11.3

**Comment by kastldratza** [comment]
Do you still have this error?

**Comment by BigYellowHammer** [comment]
Stopped using it. Decided to record it differently.
