### ISSUE TITLE
XFCE application menu overlays the recording

### ISSUE THREAD

**Issue by russwilliston** [kastldratza/zoomrec#39]
After the recording starts, the XFCE application menu is left open and it overlays the recording.  (Works great otherwise -- this is really helpful!)
![sample issue](https://user-images.githubusercontent.com/4135949/196243884-a1de8453-59ed-4f43-ab0f-6255506ffce4.png)

**Comment by russwilliston** [comment]
Tinkering with this:  I think the zoom session is supposed to be fullscreen at this point.  I believe the button to click to enter fullscreen in Zoom may have changed this year-- it's no longer "Enter Fullscreen" it's just "Fullscreen."   I think supplying a new image may fix it.

**Comment by russwilliston** [comment]
I worked around this issue by editing the python script -- I reduced the confidence for speaker_view.jpg to 50, and then parked the cursor at (0,100) instead of (0,50).   That creates a good recording for now.

**Comment by kastldratza** [comment]
Hi @russwilliston 
Thanks for pointing out the problem and describing a workaround.
I have already fixed it and will publish it soon.
