### ISSUE TITLE
Failed to connect to session manager: Failed to connect to the session manager: SESSION_MANAGER environment variable not defined

### ISSUE THREAD

**Issue by JohannesBoll** [kastldratza/zoomrec#41]
Hi,

I tried to run the docker container and record a zoom meeting following the instructions from the repo, but it didnt worked. The dcoker logs show the following:
```
DISPLAY = :1
VNC_COL_DEPTH = 24
VNC_RESOLUTION = 1024x576
VNC_IP = 172.17.0.2
VNC_PORT = 5901

Connect to 172.17.0.2:5901

Start script..
Failed to connect to session manager: Failed to connect to the session manager: SESSION_MANAGER environment variable not defined
```

How can I fix that?

Best

**Comment by kastldratza** [comment]
Hi,
this error message is always output, but has no effect on zoomrec. You can simply ignore it.
* #21
* #37
