### ISSUE TITLE
issue with meeting where host has enabled recording

### ISSUE THREAD

**Issue by vanishinggradient** [kastldratza/zoomrec#42]
for meeting with recording, It requires accepting a prompt on the dialog and connecting to the meeting with computer audio (a prompt). I had to do it manual using vnc viewer

**Describe the solution you'd like**

A automated method to record meetings (esp. one in a different timezone) that accepts those dialogs

**Comment by kastldratza** [comment]
Thanks for reporting!
That's already implemented, but maybe the dialog is different now. Could you please add a screenshot of the dialog?

**Comment by vanishinggradient** [comment]
It fails to connect to audio

![2022-11-26_13-59-36-Data Pre-Processing and Data Wrangling_join_audio_error](https://user-images.githubusercontent.com/61178871/204080605-21e9aeb8-b9f1-463c-a08e-a852967cb19a.png)

```meetings.csv
weekday;time;duration;id;password;description;record
saturday;14:00;120;85140122330;eXVaS01xU09jcnR3aVBXNXVDc3ptZz09;Data Pre-Processing and Data Wrangling;true
```
```
docker run -d --restart unless-stopped  -e TZ=Asia/Kolkata -e DEBUG=True -v ${PWD}/recordings:/home/zoomrec/recordings -v ${PWD}/audio:/home/zoomrec/audio -v ${PWD}/meetings.csv:/home/zoomrec/meetings.csv:ro -p 5901:5901 --security-opt seccomp:unconfined kastldratza/zoomrec:latest
```


```logs.txt
2022-11-26 13:43:32 
2022-11-26 13:43:32 DISPLAY = :1
2022-11-26 13:43:32 VNC_COL_DEPTH = 24
2022-11-26 13:43:32 VNC_RESOLUTION = 1024x576
2022-11-26 13:43:32 VNC_IP = 172.17.0.2
2022-11-26 13:43:32 VNC_PORT = 5901
2022-11-26 13:43:35 
2022-11-26 13:43:35 Connect to 172.17.0.2:5901
2022-11-26 13:43:36 
2022-11-26 13:43:36 Start script..
2022-11-26 13:43:41 Failed to connect to session manager: Failed to connect to the session manager: SESSION_MANAGER environment variable not defined
```

**Comment by kastldratza** [comment]
The screenshot does not show the dialog where the host has enabled recording.
What is your actual problem?

**Comment by hovo1990** [comment]
Hi, Thanks for the awesome tool.
I am also having issues with recording.
Here is the screenshot (Sorry for the low quality):

![image](https://user-images.githubusercontent.com/7003230/205155828-188d35b3-e9cc-464c-9886-e51ef3fb434e.png)

**Comment by vanishinggradient** [comment]
> The screenshot does not show the dialog where the host has enabled recording. What is your actual problem?

sorry should have created a new issue for this one (audio one)

but I had the same issue as hovo1990 when I join a zoom recording

**Comment by kastldratza** [comment]
The tool should automatically detect this message and click "Got It".

See code:
https://github.com/kastldratza/zoomrec/blob/5ddc5113ccb7263abb72f1b0199f0a2fd51ac80c/zoomrec.py#L577

**Comment by tank0226** [comment]
Seems like the check is only at the start. If the host starts recording after zoomrec joins the meeting then the check will not pick it up. Just found this interesting project by the way. Merry Xmas 🎄

**Comment by kastldratza** [comment]
Thank you! Unfortunately, I saw the message a little too late. 😆

The check is done at the beginning and continuously in the BackgroundThread, so it should work:
https://github.com/kastldratza/zoomrec/blob/5ddc5113ccb7263abb72f1b0199f0a2fd51ac80c/zoomrec.py#L90
