### ISSUE TITLE
Zoomrec is unable to enter email address

### ISSUE THREAD

**Issue by UnlimitedCookies** [kastldratza/zoomrec#44]
**Describe the bug**
![image](https://user-images.githubusercontent.com/49200216/203561028-422bafdc-09b6-4bb7-9de9-072cdd5a67cb.png)

If I connect to the VNC, I am able to observe that Meeting ID and Password are entered, but then zoomrec is not able to join the meeting due to the missing email address field. 

If I manually enter something, the script closes zoom afterwards.

**Comment by kastldratza** [comment]
Should work again with #45

**Comment by UnlimitedCookies** [comment]
Sounds good, roughly when will this get merged?
