### ISSUE TITLE
Can not run zoom directly in Linux (via VNC)

### ISSUE THREAD

**Issue by thuongta** [kastldratza/zoomrec#47]
**Describe the bug**
Please help me check issue I can not execute zoom GUI directly in Linux (via VNC)

**To Reproduce**
Steps to reproduce the behavior: (as attached file)
![vncviewer_bEDCjNaWQI](https://user-images.githubusercontent.com/105351520/207226925-996508d1-4e5a-4d44-8ded-586b4b024271.gif)

**Desktop (please complete the following information):**
I am using Docker Desktop 4.15.0 (93002) is currently the newest version available.
![docker desktop release](https://user-images.githubusercontent.com/105351520/207227208-86931137-815f-4bd6-8d09-4677a9312b0d.png)

![Docker Engine](https://user-images.githubusercontent.com/105351520/207227882-03602952-fe46-463d-b599-9c8bafd14e04.png)

![General config](https://user-images.githubusercontent.com/105351520/207227966-b32ee00c-f58e-470e-8be0-615299560126.png)

Thanks your support !

**Comment by kastldratza** [comment]
Hi @thuongta, do you still have this problem?
I have tested the current Docker image and it works.
Can you try using `docker pull kastldratza/zoomrec:latest` to load the current image and then test it again?

If that doesn't work either, open a terminal in zoomrec and try to run zoom from the command line.
If that results in an error, feel free to forward it to me.

**Comment by oulmachev** [comment]
Hi @thuongta, I think I experienced the same behaviour recently and temporarily fixed it by specifying an older version of Zoom client here:
https://github.com/kastldratza/zoomrec/blob/5ddc5113ccb7263abb72f1b0199f0a2fd51ac80c/Dockerfile#L86

I changed
`wget -q -O zoom_amd64.deb https://zoom.us/client/latest/zoom_amd64.deb && \`
to
`wget -q -O zoom_amd64.deb https://cdn.zoom.us/prod/5.13.0.599/zoom_amd64.deb && \`
and then rebuild a docker image. Everything started working.

I think the issue might be with the latest Zoom client and as the version of the client is not specified, it keeps working in some images. As I understand it, when you are re-building an image, Docker keeps the Zoom client in cache and as the current URL of `https://zoom.us/client/latest/zoom_amd64.deb` is not changing with image re-builds it keeps using an older version.
