### ISSUE TITLE
Cannot start Docker Container: SESSION_MANAGER environment variable not defined

### ISSUE THREAD

**Issue by ThanhTungRedAnt** [kastldratza/zoomrec#52]
First of all, I would like to thank everyone who came up with the Bot record Zoom solution
I'm trying to run the docker image version on docker hub and got this error, hope to get some feedback and help.

OS: MacOS
Docker: Docker version 20.10.22, build 3a2c30b

Start script:

docker run
-e TZ=Asia/Ho_Chi_Minh
-v $(pwd)/recordings:/home/zoomrec/recordings
-v $(pwd)/example/audio:/home/zoomrec/audio
-v $(pwd)/example/meetings.csv:/home/zoomrec/meetings.csv:ro
-p 5901:5901
--security-opt seccomp:unconfined
kastldratza/zoomrec:latest

Container Log

DISPLAY = :1
VNC_COL_DEPTH = 24
VNC_RESOLUTION = 1024x576
VNC_IP = 172.17.0.2
VNC_PORT = 5901

Connect to 172.17.0.2:5901

Start script..
Failed to connect to session manager: Failed to connect to the session manager: SESSION_MANAGER environment variable not defined

**Comment by tfiechowski** [comment]
@ThanhTungRedAnt did you manage to solve this issue?
