### ISSUE TITLE
Allow specific date to be set instead of a "weekday"

### ISSUE THREAD

**Issue by Keanu73** [kastldratza/zoomrec#55]
**Is your feature request related to a problem? Please describe.**
I'd like to put specific dates for meetings in the CSV file, instead of having to put in a weekday, so that I can use `zoomrec` to record one-off Zoom meetings.

**Describe the solution you'd like**
The addition of a `date` column, and perhaps a `weekly`/`regular` boolean column to allow the toggle of regularly joining the same meeting or not.

**Comment by derp90** [comment]
I would also love this feature, but because it's marked as stale I will open a new request
