### ISSUE TITLE
Feature wishlist

### ISSUE THREAD

**Issue by bevenky** [kastldratza/zoomrec#6]
1. This works on AWS using terraform using docker
2. Play Recording audio at the start of joining a call
3. Join a conference recording automatically by looking up a calendar for the meeting - Google Calendar - see scheduler.py https://github.com/andycasey/zoomerang
4. Add support to record Google Meet, MS Teams, Cisco WebEx calls too.
5. Benchmark for how many of these docker instances can be run on one standard AWS machine type? Basically if one wanted to record 1000 sessions how can we make that happen?
6. Ability to monitor recordings sessions in various containers

**Comment by kastldratza** [comment]
**First of all, thank you very much for your ideas!**

Below i have added some thoughts and initial to-dos.

1. How would it be possible to make this work on AWS/Digital Ocean?

> To run zoomrec on **AWS** you can simply set up the Elastic Container Service. However, the container requires additional storage for the recordings. For this, a volume of AWS EFS or AWS EBS can be used. Afterwards, the recordings could be synced to an S3 bucket to save money.
> To get it work on **Digital Ocean** I'll need to look it up first.

2. Play Recording audio at the start of joining a call
> To play a recording at the beginning of a call, the audio file could be played with ffplay (already installed with ffmpeg), another media player or a suitable python module.

3. Join a conference recording automatically by looking up a calendar for the meeting - Google Calendar - see scheduler.py https://github.com/andycasey/zoomerang
> Possible, but needs some research first.

4. Add support to record Google Meet, MS Teams, Cisco WebEx calls too.
> Already had the same idea :+1: 
> Not sure if it would be better to create separate projects per variant or not. What do you think?

5. Benchmark for how many of these docker instances can be run on one standard AWS/DO machine type? Basically if one wanted to record 1000 sessions how can we make that happen?
> Needs to be tested/done. AWS ECS could be used here too (Default quota value: _Container instances per cluster_ = 2.000).
> But here you would need some logic in deployment/starting process.

6. Ability to monitor recordings sessions in various containers
> Any ideas for this? Maybe some kind of api to fetch status of zoomrec or something?

Happy to pay for this work and support the project. You can also email me at venky at plivo dot com if you want to discuss over an email.
> Thank you in advance! I'll contact you.

---

**TODOs**
 - [ ] Research & Thoughts
 - [ ] Check used resources of one
   - [ ] running
   - [ ] idle
 - [ ] Calculate for more and check machine types of
   - [ ] AWS
   - [ ] DO

**Comment by bevenky** [comment]
@kastldratza so what are next steps here? Can we take this discussion over email.

Following are my notes for the points below:


> 1. How would it be possible to make this work on AWS/Digital Ocean?
> 
> > To run zoomrec on **AWS** you can simply set up the Elastic Container Service. However, the container requires additional storage for the recordings. For this, a volume of AWS EFS or AWS EBS can be used. Afterwards, the recordings could be synced to an S3 bucket to save money.
> > To get it work on **Digital Ocean** I'll need to look it up first.

Can we prioritize AWS ECS with Terraform and use AWS EBS + S3 after recording to sync it. This can be the first priority task.
 
> 1. Play Recording audio at the start of joining a call
> 
> > To play a recording at the beginning of a call, the audio file could be played with ffplay (already installed with ffmpeg), another media player or a suitable python module.

Ok. Can we pick this up as the second task as a configuration to start with. Ability to pick from one of the 3 audio files. 

> 1. Join a conference recording automatically by looking up a calendar for the meeting - Google Calendar - see scheduler.py https://github.com/andycasey/zoomerang
> 
> > Possible, but needs some research first.

Let me know how we can do this as this is important for the best customer experience.

> 1. Add support to record Google Meet, MS Teams, Cisco WebEx calls too.
> 
> > Already had the same idea 👍
> > Not sure if it would be better to create separate projects per variant or not. What do you think?

I think it's best to add these within the same project as different modules/folders. 

> 1. Ability to monitor recordings sessions in various containers
> 
> > Any ideas for this? Maybe some kind of api to fetch status of zoomrec or something?
> 

Best to have a combination of APIs and webhooks that update the status to a URL.

**Comment by rsun0013** [comment]
1. The ability to join breakout rooms automatically when invited, this should be similar to some of the other options already present.
