### ISSUE TITLE
Video saving but only less than one second

### ISSUE THREAD

**Issue by colindaly** [kastldratza/zoomrec#73]
**Describe the bug**
Video saving but only less than one second.

**Expected behavior**
Expected to run the full length of the meeting.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 22
 - Docker image

**Additional context**
Any possibility to record audio only?

**Comment by jnamyslo** [comment]
Hi,
I have the same problem here. After some trail and error I tried to join a meeting manually - it seems like there is an issue with the installed Zoom Client Version (see screenshot below). 
Unfortunately I don't know how to update it or if it is even possible.
![Screenshot 2024-03-25 131147](https://github.com/kastldratza/zoomrec/assets/141773912/e328d03a-e205-4c7c-81e1-2c54c7b702de)
