### ISSUE TITLE
SESSION_MANAGER environment variable not defined

### ISSUE THREAD

**Issue by cschwarz007** [kastldratza/zoomrec#76]
**Describe the bug**
The container is starting over and over, produces this log output:

```
DISPLAY = :1
VNC_COL_DEPTH = 24
VNC_RESOLUTION = 1024x576
VNC_IP = 172.17.0.12
VNC_PORT = 5901

Connect to 172.17.0.12:5901

Start script..
Failed to connect to session manager: Failed to connect to the session manager: SESSION_MANAGER environment variable not defined
```

**To Reproduce**
1. Install as instructed
2. Start container

**Expected behavior**
Container starts and keeps on running

**Desktop (please complete the following information):**
 - Docker Standalone 20.10.3 on Linux
 - Chrome
 - Version 123

**Comment by Dreak183** [comment]
Same issue here.

**Comment by derp90** [comment]
@cschwarz007  @Dreak183 did you ever solve this?
