### ISSUE TITLE
zoom recording

### ISSUE THREAD

**Issue by den1k** [kastldratza/zoomrec#8]
Can't get it to run :/ any idea what I'm doing wrong

```
docker logs 95131121d20b -f

DISPLAY = :1
VNC_COL_DEPTH = 24
VNC_RESOLUTION = 1024x576
VNC_IP = 172.17.0.2
VNC_PORT = 5901

Connect to 172.17.0.2:5901

Start script..
Failed to connect to session manager: Failed to connect to the session manager: SESSION_MANAGER environment variable not defined

DISPLAY = :1
VNC_COL_DEPTH = 24
VNC_RESOLUTION = 1024x576
VNC_IP = 172.17.0.2
VNC_PORT = 5901

Connect to 172.17.0.2:5901

Start script..
Failed to connect to session manager: Failed to connect to the session manager: SESSION_MANAGER environment variable not defined

DISPLAY = :1
VNC_COL_DEPTH = 24
VNC_RESOLUTION = 1024x576
VNC_IP = 172.17.0.2
VNC_PORT = 5901

Connect to 172.17.0.2:5901
E: [pulseaudio] main.c: Daemon startup failed.

DISPLAY = :1
VNC_COL_DEPTH = 24
VNC_RESOLUTION = 1024x576
VNC_IP = 172.17.0.2
VNC_PORT = 5901

Connect to 172.17.0.2:5901
E: [pulseaudio] main.c: Daemon startup failed.

DISPLAY = :1
VNC_COL_DEPTH = 24
VNC_RESOLUTION = 1024x576
VNC_IP = 172.17.0.2
VNC_PORT = 5901

Connect to 172.17.0.2:5901
E: [pulseaudio] main.c: Daemon startup failed.

DISPLAY = :1
VNC_COL_DEPTH = 24
VNC_RESOLUTION = 1024x576
VNC_IP = 172.17.0.2
VNC_PORT = 5901

Connect to 172.17.0.2:5901
E: [pulseaudio] main.c: Daemon startup failed.

DISPLAY = :1
VNC_COL_DEPTH = 24
VNC_RESOLUTION = 1024x576
VNC_IP = 172.17.0.2
VNC_PORT = 5901

Connect to 172.17.0.2:5901
E: [pulseaudio] main.c: Daemon startup failed.

DISPLAY = :1
VNC_COL_DEPTH = 24
VNC_RESOLUTION = 1024x576
VNC_IP = 172.17.0.2
VNC_PORT = 5901

Connect to 172.17.0.2:5901
E: [pulseaudio] main.c: Daemon startup failed.

DISPLAY = :1
VNC_COL_DEPTH = 24
VNC_RESOLUTION = 1024x576
VNC_IP = 172.17.0.2
VNC_PORT = 5901

Connect to 172.17.0.2:5901
E: [pulseaudio] main.c: Daemon startup failed.

DISPLAY = :1
VNC_COL_DEPTH = 24
VNC_RESOLUTION = 1024x576
VNC_IP = 172.17.0.2
VNC_PORT = 5901

Connect to 172.17.0.2:5901
E: [pulseaudio] main.c: Daemon startup failed.

DISPLAY = :1
VNC_COL_DEPTH = 24
VNC_RESOLUTION = 1024x576
VNC_IP = 172.17.0.2
VNC_PORT = 5901

Connect to 172.17.0.2:5901
E: [pulseaudio] main.c: Daemon startup failed.
```

**Comment by kastldratza** [comment]
How did you start the container? It could be that the access to the volume does not work.

**Comment by den1k** [comment]
I tried a lot of things including using the exact directions from the readme with a chowned recordings folder and meetings.csv from the example folder:

```
docker run -d --restart unless-stopped \
  -e TZ=Europe/Berlin \
  -v $(pwd)/recordings:/home/zoomrec/recordings \
  -v $(pwd)/example/meetings.csv:/home/zoomrec/meetings.csv:ro \
  -p 5901:5901 \
kastldratza/zoomrec:latest
```

I also bash'ed into the instance using `docker exec -it <container-id> bash`. As far as I could tell–and I read most of the code by now–all files where there.

**Comment by den1k** [comment]
Had also added a log to the top of `zoomrec.py`. It doesn't seem to even get there. I think the error comes up in starting `xfce-terminal`

**Comment by den1k** [comment]
I tried to VNC into it through MacOS's Finder which also did not work.

**Comment by kastldratza** [comment]
@den1k I'll try to reproduce the error and let you know.

**Comment by kastldratza** [comment]
I used the command from the readme and started the container successfully. After that I could connect to the container with the MacOS Finder using the address '**vnc://127.0.0.1:5901**'. So i can not reproduce your problem.
If you use the command you mentioned above, you must be in the root folder of the repository!

**Comment by den1k** [comment]
It turns out I was missing the`vnc://` part of the uri. The sessionmanager env variable missing does not seem to be an issue.

Thanks for trying to repro!

**Comment by Robin-Bakker** [comment]
For future reference: I ran into the same issue, and it turned out to be caused by mistyping the bind mount.

I originally used the following docker run command:

```
docker run -d --restart unless-stopped \
-e TZ=Europe/Amsterdam \
-v ${pwd}/recordings:/home/zoomrec/recordings \
-v ${pwd}/meetings.csv:/home/zoomrec/meetings.csv:ro \
-p 5901:5901 \
kastldratza/zoomrec:latest
```

I used this command on Ubuntu, but it is intended for Powershell. Replacing `${pwd}` with `$(pwd)` fixed the issue for me.

Thanks for the program!

**Comment by Foxtrod89** [comment]
Can't record session. Operation not permitted.

**Comment by kastldratza** [comment]
@Foxtrod89 Did you set permissions correctly as described in the ReadMe?
