### ISSUE TITLE
Q: using zoom's native recording feature

### ISSUE THREAD

**Issue by den1k** [kastldratza/zoomrec#9]
@kastldratza I'm looking into using zoom's native recording feature instead of ffmpeg to record the screen. Before I go down that rabbithole I was curious if you have tried this and IF you did whether you abandoned it in favor of ffmpeg?

**Comment by den1k** [comment]
It's definitely possible if zoomrec supported user/pw params in order to log in with an account that has recording privileges.

**Comment by kastldratza** [comment]
Added 'Sign In to existing Zoom account' to Roadmap. After that, a workflow can be implemented for using the native recording.
